config/routes.rb
Rails.application.routes.draw do
  root 'main#home'
  get '/cookie_hack' => 'main#cookie_hack'

  post '/pablo' => 'pablo#pablo'
  post '/hook' => 'pablo#pablo'
  get '/pablo_test' => 'pablo#pablo'
  get '/boba' => 'pablo#boba'
  get '/pablo/admin'=>'pablo#admin'
  post '/pablo/send/:id' => 'pablo#admin_send'
  get '/hook' => 'pablo#hook'
  get '/pablo' => 'pablo#hook'
  get '/pablo/broadcast' => 'pablo#admin_broadcast'
  post '/pablo/broadcast' => 'pablo#broadcast'

  get "/auth/google_oauth2/callback", to: "auth#google_callback"
  get '/auth/email', to:'auth#email'
  get "/auth/logout", to: "auth#logout"
  get '/unauthorized', to: 'application#unauthorized'

  get 'me' => 'members#me'
  get 'members' => 'members#index'
  post 'me/update' => 'members#update'
  post 'me/update_commitments' => 'members#update_commitments'

  get ':key/go' => 'go#redirect'
  get ':key/go/redirect' => 'go#redirect'
  get 'go/redirect/:key' => 'go#redirect'
  get 'go' => 'go#index'
  get 'go/menu' => 'go#index'
  get 'go/redirect' => 'go#index'
  get 'go/ajax_scroll/:page' => 'go#ajax_scroll'
  get 'go/show/:id' => 'go#show'
  get 'go/search' => 'go#search'
  get 'go/add' => 'go#add'
  post 'go/update' => 'go#update'
  post 'go/destroy/:id' => 'go#destroy'
  get 'go/lookup' => 'go#lookup'
  
  post 'go/batch_update_groups' => 'go#batch_update_groups'
  post 'go/add_checked_id' => 'go#add_checked_id'
  post 'go/remove_checked_id' => 'go#remove_checked_id'
  get 'go/get_checked_ids' => 'go#get_checked_ids'
  get 'go/ajax_get_checked' => 'go#ajax_get_checked'
  get 'go/deselect_links' => 'go#deselect_links'
  get 'go/delete_checked' => 'go#delete_checked'

  get 'go/trash' => 'go#trash'
  post 'go/restore/:id' => 'go#restore'
  post 'go/destroy_copy/:id' => 'go#destroy_copy'

  get 'blog' => 'blog#index'
  get 'blog/ajax_scroll/:page' => 'blog#ajax_scroll'
  get 'blog/show/:id' => 'blog#show'
  get 'blog/edit' => 'blog#edit'
  get 'blog/email/:id' => 'blog#email'
  get 'blog/post/:id' => 'blog#post'
  post 'blog/save' => 'blog#save'
  get 'blog/destroy/:id' => 'blog#destroy'
  post 'blog/send_email/:id' => 'blog#send_email'
  get 'blog/comments/:id' => 'blog#comments'
  post 'blog/post_comment/:id' => 'blog#post_comment'
  post 'blog/delete_comment/:id' => 'blog#delete_comment'
  get 'blog/push_post/:id' => 'blog#push_post'

  get 'tabling' => 'tabling#index'
  post 'tabling/switch' => 'tabling#switch'
  get 'tabling/confirm_switch/:id' => 'tabling#confirm_switch'
  get 'tabling/generate' => 'tabling#generate'
  get 'tabling/schedules' => 'tabling#schedules'
  post 'tabling/admin_switch' => 'tabling#admin_switch'
  get 'tabling/slots_available' => 'tabling#slots_available'
  get 'tabling/chair_tabling' => 'tabling#chair_tabling', as: 'chair_tabling'
  
  get 'push' => 'push#index'
  get 'push/register'  => 'push#register'
  get 'push/new' => 'push#new'
  post 'push/create' => 'push#create'

  get 'points' => 'points#attendance'
  get 'points/scoreboard' => 'points#scoreboard'
  get 'points/distribution' => 'points#distribution'
  get 'points/attendance' => 'points#attendance'
  post 'points/mark_attendance' => 'points#mark_attendance'
  get 'pull_events' => 'points#pull_events'

  get 'groups' => 'groups#index'
  post 'groups/create' => 'groups#create'
  get 'groups/destroy/:id' => 'groups#destroy'
  get 'groups/edit/:id'=>'groups#edit'
  post 'groups/update/:id'=>'groups#update'
  get 'groups/new' => 'groups#new'

  get 'clicks' => 'clicks#index'

end

app/controllers/tabling_controller.rb
class TablingController < ApplicationController
	before_filter :is_member
	
	def slots_available
		@members = Member.active
			.where.not(committee:'GM')
			.order(:committee)
	end

	def chair_tabling
		@starting_slots = TablingManager.starting_slots
		@slots = TablingManager.default_slots
		@availabilities = TablingManager.slot_availabilities
	end

	def index
		@me = current_member
		slots = TablingSlot
			.order('time ASC')
			.all.to_a
		@slot_hash = {}
		slots.each do |slot|
			day = slot.get_day
			if not @slot_hash.keys.include?(day)
				@slot_hash[day] = []
			end
			@slot_hash[day] << slot
		end
		@switch_requests = TablingSwitchRequest.where('email1 = ? OR email2 = ?', 
			@me.email,
			@me.email
		)
		@email_hash = Member.email_hash

		track_click("Tabling", nil)
	end

	# post a switch request
	def switch
		if not current_member
			render nothing: true, status: 500
		else
			member2 = Member.where('lower(name) = ?', params[:name].downcase)
				.where(latest_semester: Semester.current_semester).first
			if member2 == nil
				render nothing: true, status: 500
			else
				member1 = current_member
				TablingSwitchRequest.where('email1 = ? OR email2 = ? OR email1=? OR email2 = ?',
					member1.email,
					member1.email,
					member2.email,
					member2.email
				).destroy_all
				switch_request = TablingSwitchRequest.where(
					email1: member1.email,
					email2: member2.email
				).first_or_create
				render nothing: true, status: 200
			end
		end
	end

	# admin can switch two members' tabling slots
	def admin_switch
		m1 = Member.where('lower(name) = ?', params[:name1].downcase).first
		m2 = Member.where('lower(name) = ?', params[:name2].downcase).first
		TablingManager.switch_tabling(m1.email, m2.email)
		render nothing: true, status: 200
	end

	# Member confirms switch with another person
	def confirm_switch
		request = TablingSwitchRequest.find(params[:id])
		TablingManager.switch_tabling(request.email1, request.email2)
		request.destroy
		redirect_to '/tabling'
	end

	# generates a new tabling schedule, deleting the old
	def generate
		if TablingManager.tabling_admin.include?(myEmail)
			TablingManager.gen_tabling
			redirect_to '/tabling'
		else
			render :template => 'members/unauthorized'
		end
	end

	def schedules
		members = Member.where(latest_semester: Semester.current_semester)
			.where.not(committee:'GM').to_a

		slots = TablingManager.default_slots
		@slots = slots
		@free_hash = {}
		slots.each do |slot|
			free = members.select{|x| x.get_commitments.include?(slot)}.map{|x| x.email}
			@free_hash[slot] = free
		end			
		@members = members
		@email_hash = Member.email_hash

	end
end

app/helpers/tabling_helper.rb
module TablingHelper
end

app/views/tabling/old stuff/chair_tabling.html.erb
<h1>
	Chair/CM Tabling Availabilities
</h1>
<% @availabilities.keys.each do |slot| %>
<div>
	<div class = 'row'>
		<h4><%= TablingSlot.get_time_string(slot) %></h4>
		<div class = 'col-md-3'>
			<h5>Chairs</h5>
			<% @availabilities[slot][:chairs].each do |chair| %>
				<div><%= chair.name %></div> 
			<% end %>
		</div>
		<div class = 'col-md-3'>
			<h5>CMs</h5>
			<% @availabilities[slot][:cms].each do |chair| %>
				<div><%= chair.name %></div> 
			<% end %>
		</div>
	</div>
</div>
<% end %>

app/views/tabling/old stuff/index.html.erb
<style style ='text/css'>
.day{
	float:left;
	width:20%;
}
</style>


<div>
<% @switch_requests.each do |request| %>
<div>Request to switch <%= @email_hash[request.email1].name %> with <%= @email_hash[request.email2].name %></div>
	<% if request.email2 == @me.email %>
		<a href = '/tabling/confirm_switch/<%= request.id %>'>Confirm Switch with <%= @email_hash[request.email1].name %></a>
	<% end %>
<% end %>

<% if @me.is_admin? %>
	<div class = 'btn btn-info' id = 'admin-switch-btn'>
	Admin Switch Tabling</div>
	<div>
		<%= link_to 'Check tabling slot availabilities', chair_tabling_path %>
	</div>
<% end %>
</div>
<h1>Tabling Schedule</h1>
<div id = 'switch-btn' class = 'btn btn-default'>Switch tabling</div>

<p>
	<a href = '/tabling/slots_available'>Check here for who to switch with</a>
</p>




<div class = 'row'>
<% @slot_hash.keys.each do |day| %>

	<div class = 'day'>
	<% @slot_hash[day].each do |slot| %>
		<div class = 'hour-div'>
			<div class = 'label label-info'>
			<%= slot.time_string %>
			</div>
			<% slot.member_emails.each do |email| %>
				<div><%= @email_hash[email].name %></div>
			<% end %>
		</div>
	<% end %>
	</div>

<% end %>
</div>


<script type = 'text/javascript'>
$('#admin-switch-btn').click(function(){
	var x = prompt("Enter both names (comma separated)", 'Justin Bieber, Selena Gomez');
	if(x){
		x = x.split(',');
		name1 = x[0].trim();
		name2 = x[1].trim();
		$.ajax({
			url:'/tabling/admin_switch',
			type:'POST',
			data:{
				name1: name1,
				name2: name2
			},
			success:function(data){
				location.reload();
			}
		})

	}
})
$('#switch-btn').click(function(){
	var x = prompt("Who do you want to switch with? (this will override any previous switch requests)");
	if(x){
		$.ajax({
			url:'/tabling/switch',
			type:'POST',
			data:{
				name: x,
			},
			success:function(data){
				location.reload();
			},
			error:function(data){
				alert('invalid switchee');
			}
		})
	}
});
</script>

app/views/tabling/old stuff/schedules.html.erb
<% @free_hash.keys.each do |time| %>
<div class = 'col-md-2'>
<h4><%= TablingSlot.get_time_string(time) %></h4>
<% @free_hash[time].each do |email| %>
	<div><%= @email_hash[email].name %></div>
<% end %>
</div>
<% end %>

app/views/tabling/old stuff/slots_available.html.haml
:css
	.commitments-div{
		max-height:100px;
		overflow:auto;
	}
	.hilite{
		background-color:rgba(100,0,0,0.1);
	}
%table{:class => 'table table-condensed table-bordered'}
	%thead
		%th Name
		%th Committee
		%th Slots available
	%tbody
	- @members.each do |member|
		%tr{:class => (member.commitments and member.commitments.length) <= 1 ? 'hilite' : ''}
			%td= member.name
			%td= member.committee
			%td
				%div{:class => 'commitments-div'}
					- member.commitments.each do |c|
						%div= TablingSlot.get_time_string(c)